### PR TITLE
add checkpoints up to block 1,410,000

### PR DESCRIPTION
**Pull request by linki**
**For clarification:** It's not my my child, I just happen to be the only maintainer.

Adds checkpoints up until May 4th 2017. This is what most other clients discoverable via `dnsseed.earthcointools.org` agree on (all but one). Specifically included the block that Wu Zen mentioned [on bitcointalk](https://bitcointalk.org/index.php?topic=379236.msg18754759#msg18754759).

### CODE REVIEW

**Comment by linki** [comment]
> [12.05.17, 04:42:14] Zen Wu: Hi Linki
[12.05.17, 04:42:48] Zen Wu: I checked my wallet, getblockhash 1410000, 7512574ec717d46a90b8c36fd923ef819fdc298b8e4be57be631519662f0db59
[12.05.17, 04:43:55] Zen Wu: that's right

Those checkpoints are confirmed by Zen Wu.

**Comment by wsl20777** [comment]
Earthcoin coins is your child, and you give up so irresponsibly?

**Comment by beyond230** [comment]
Three options.
1, pos turn.
2. the merger and mining are combined.
3, upgrade the new version of bitcoin core.

**Comment by linki** [comment]
**For clarification:** It's not my my child, I just happen to be the only maintainer.

**Comment by linki** [comment]
@bulaimei00 @wsl20777 @beyond230 Thanks for your inputs.

@wsl20777 I don't understand. Please explain what you mean as soon as possible.

@beyond230 There aren't any major changes planned for EarthCoin from my side. We invite intersted people in getting involved in project.

@bulaimei00 There will binary releases as soon as I'll have the time to build them. Zen Wu will announce them.

**Comment by wsl20777** [comment]
Please be concerned about EAC, one more concern, one more responsibility.

**Comment by 596042055** [comment]
We Need U Continue to Develop EarthCoin

**Comment by bulaimei00** [comment]
Thank you for your answer! The earthcoin is very popular in China. We can exchange earthcoin in www.btc38.com and daily turnover is great.Chinese earthcoin community lovers do public service in China. We love earthcoin and we hopes you can update earthcoin.

**Comment by linki** [comment]
> linki commented 4 days ago • edited
[...] I just happen to be the only maintainer.

This came out wrong. I meant: *I happen to be the only **code-related** maintainer*.

**Zen Wu** is doing a great job in every other area!

**Comment by 596042055** [comment]
wake up!  linki,  continue  to  develop

**Comment by 596042055** [comment]
welcome to  join the  slack:  earthcoin.slack.com

**Pull request merged**
